### PR TITLE
issue #1, improve performance

### PR DESCRIPTION
**Pull request by jiaohaibin**
do not add neighbor which already has label into neighbors again

### CODE REVIEW

**Comment by mattt** [comment]
Thanks so much for submitting this PR, @jiaohaibin! I made a few small changes, including fcea49e, which switches the order of the `&&` expression to short-circuit on the less expensive equality check, making `distanceFunction` conditionally executed.

**Comment by mattt** [comment]
Although this behavior is likely faster, I'm not 100% certain that it always produces correct behavior. My implementation was a translation of the pseudocode in [the Wikipedia article](https://en.wikipedia.org/wiki/DBSCAN). Without a robust test suite, I don't have strong confidence in this change...

@jiaohaibin  Do you know of any data sets that I might incorporate into more unit tests?

**Comment by jiaohaibin** [comment]
Hi Mattt,

Thanks for your review and advice.
I am testing using the GPS location positions of my photo library.
How about to generate a data set with random data and compare the result with change and without change?

Best Regards,
Haibin

**Comment by jiaohaibin** [comment]
Hi Mattt,

I uploaded my GPS location test data to [https://photovault-test.oss-cn-shanghai.aliyuncs.com/gps.csv](https://photovault-test.oss-cn-shanghai.aliyuncs.com/gps.csv)

Best Regards,
Haibin

**Comment by mattt** [comment]
Thanks for sharing that, @jiaohaibin.

I added a different dataset to verify behavior and test performance with #3. Rebasing #2 against the latest HEAD of main, `testCapitalsPerformance` shows a change in results (31 clusters instead of 12, with 39 outliers instead of 33). The performance difference is 0.009 sec against a baseline of 0.022 sec.

Without a testable reference implementation or verified results, I don't know which one is right. Do you know if there's a golden standard implementation out there that we could use for comparison?

**Comment by mattt** [comment]
Closing this until we have a way to verify both correct behavior and improved performance.

@jiaohaibin Let me know if you're interested in working on this further, and I'd be happy to reopen.

**Pull request closed without merging**
